### ISSUE TITLE
Loader error after upgrade to 0.9.2

### ISSUE THREAD

**Issue by TynesideGroup** [xkjyeah/vue-google-maps#387]
Just upgraded to 0.9.2 (from 0.8.11) and have the following error upon building my Nuxt project:

![image](https://user-images.githubusercontent.com/20924299/38938315-231549ac-431d-11e8-903c-7f57e8b304ee.png)

This appears to be related to https://github.com/xkjyeah/vue-google-maps/issues/138

My `nuxt.config.js` file has the following webpack config to deal with a previous issue I had with vue2-google-maps and it has worked fine up to now:

```js
config.module.rules.splice(0, 0, {
  test: /\.js$/,
  include: /(node_modules\/vue2-google-maps)/,
  loader: 'babel-loader'
})
```

The error points to the spread operator used for `...options` but I have tried updating my config to the following (both `babel-preset-env` and `babel-plugin-transform-object-rest-spread` are available in `node_modules`) but it did not work:

```js
config.module.rules.splice(0, 0, {
  test: /\.js$/,
  include: /(node_modules\/vue2-google-maps)/,
  loader: 'babel-loader',
  options: {
    preset: ['env'],
    plugins: ['transform-object-rest-spread']
  }
})
```

Any suggestions?

**Comment by xkjyeah** [comment]
Compatibility with Nuxt 1.4 is still WIP unfortunately! Sorry, if you know
how to fix it, I'll take a PR.

**Comment by xkjyeah** [comment]
I've updated the README.md with instructions. Please take a look and see if it helps you. :)

**Comment by TynesideGroup** [comment]
@xkjyeah I have updated to 0.9.5 and used the config you have provided but unfortunately this does not work - the same error persists.

**Comment by xkjyeah** [comment]
The instructions have changed slightly since. Try importing from
'vue2-google-maps' instead of 'vue2-google-maps/src/main'

**Comment by TynesideGroup** [comment]
I've updated my plugin to us `vue2-google-maps` instead of `vue2-google-maps/src/main` and it works great now - thanks!
