### ISSUE TITLE
Could anyone use vue-google-maps in IE11?

### ISSUE THREAD

**Issue by HKskn** [xkjyeah/vue-google-maps#401]
Hi, the library works well with other browsers but in IE11 it doesn't work i get always syntax error, i tried everything i found on the internet but i didn't solve. It seems transpiling problem.

I'm using vue cli 2.9.3.

**Comment by xkjyeah** [comment]
Try to add the babel-polyfill library to your webpack entry point

**Comment by HKskn** [comment]
@xkjyeah  Thanks for reply but I have already added it. Still it doesn't work.
`entry: {
    app: ['babel-polyfill',path.resolve(__dirname, '../src/main.js')]
  },`

**Comment by HKskn** [comment]
@xkjyeah before adding 'babel-polyfill', it gives vuex requires a Promise Polyfill, after adding 'babel-polyfill' to entry point, it gives Script1002: Syntax error on app.js(957 1) and when i clicked on it goes on an 'eval(long string...)' statement.

**Comment by HKskn** [comment]
@xkjyeah I solved the problem. I forked the project and changed .vue files.
`export default (x => x.default || x)(require('./mapImpl.js'))
`
statements like these are affecting ie11.
I changed them like below
`<script src="./mapImpl.js">
</script>`
I think you should find another solution to solve nuxt problem.

**Comment by xkjyeah** [comment]
Are you using Nuxt or webpack?

**Comment by xkjyeah** [comment]
If you are using Nuxt, please read the instructions on the README. I've updated it to mention the need for vendors

**Comment by HKskn** [comment]
@xkjyeah  I'm using webpack.

**Comment by xkjyeah** [comment]
Does it work in IE if you change the offending line to:

```
export default (function (x) { return x.default ||
x})(require('./mapImpl.js'))
```

**Comment by HKskn** [comment]
@xkjyeah Yes, it works with it. I think .vue files isn't compiled in this library. Somehow vue-template-compiler can't work, isn't it?

**Comment by mikaelatorn** [comment]
I'm having the exact same issue for IE11 as well. Should I fork the repo and do as @HKskn did or will there be an update to fix this problem? :)

**Comment by rokkie** [comment]
I'm also running into this. Same question as @mikaelatorn. I rather not fork but do need to support IE.

**Comment by HKskn** [comment]
@mikaelatorn @rokkie I published it as a temporary library. It's name is 'vue2-google-maps-fixed'.

**Comment by mikaelatorn** [comment]
Sadly I still have the same issue when using 'vue2-google-maps-fixed'. Any luck @rokkie ?

**Comment by HKskn** [comment]
@mikaelatorn Did you add below?

`entry: { app: ['babel-polyfill',path.resolve(__dirname, '../src/main.js')] },`

**Comment by mikaelatorn** [comment]
Yes, I'm using polyfill for another library as well @HKskn

**Comment by rokkie** [comment]
@mikaelatorn will try today and report when i have results

**Comment by rokkie** [comment]
@mikaelatorn @HKskn `vue2-google-maps-fixed` works for me in IE10 and 11. I didn't do extensie testing, but before the map wouldn't load at all and got (syntax) errors in the console. Now the map loads just fine.

**Comment by xkjyeah** [comment]
It's strange that Babel runs for other Vue files but not the Vue files in
dist. Have you changed the Babel options? E.g. to use a babelrc?

**Comment by HKskn** [comment]
@xkjyeah I didn't change it. My current config is

`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["transform-vue-jsx", "istanbul"]
    }
  }
}`

**Comment by xkjyeah** [comment]
How is your Vue-loader configured? And your babel-loader?

**Comment by xkjyeah** [comment]
Also, is Vue-loader v15? Is VueLoaderPlugin loaded?

https://vue-loader.vuejs.org/migrating.html

**Comment by HKskn** [comment]
@xkjyeah 
`'use strict';
const utils = require('./utils');
const config = require('../config');
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
    loaders: {
        ...utils.cssLoaders({
            sourceMap: isProduction ? config.build.productionSourceMap : config.dev.cssSourceMap,
            extract: isProduction
        }),
        i18n: '@kazupon/vue-i18n-loader' // vue-i18 single file component <i18> tag loader
    },
    transformToRequire: {
        video: 'src',
        source: 'src',
        img: 'src',
        image: 'xlink:href'
    }
};`

I'm using vue-loader version "13.7.1"

**Comment by taivu** [comment]
Having same issue, using vue loader v15. added it as plugin to webpack.

also configured the loader for this:
https://vue-loader.vuejs.org/migrating.html#importing-sfcs-from-dependencies
```Due to the inference change of v15, if you import a Vue SFC inside node_modules, its <script> part will be excluded from transpilation as well.```

still getting the synxtax error from the export lines in *.vue files from vue2-google-maps

**Comment by licitdev** [comment]
The fix (vue2-google-maps-fixed) by @HKskn resolved my issue of Vue CLI app on iOS 9 devices and IE11. On a side note, I already had babel-polyfill and es6-promise/auto in my project.

@xkjyeah Kudos for the plugin! Hope the fix will be merged into the vue2-google-maps.

@HKskn Thank you!

**Comment by xkjyeah** [comment]
Hi,

I've published v0.9.7 -- not exactly the same fix, but should work.

Seems like the reason the vue-loader instructions didn't work is because there wasn't a babelrc in vue-google-maps/dist, or it was blank; so following the instructions didn't affect the babel transpilation one bit.

**Comment by taivu** [comment]
not trying to be argumentative, genuinely curious, why would there be a need to have `.babelrc` in a dist folder? isnt it supposed to be settings for tooling? Appreciate all the work everyone's done!

**Comment by xkjyeah** [comment]
Haha fair question.

The reason is that there is no transpiler for just the JS-section of .Vue
files. So I was caught in a bind -- either I didn't transpile at all, which
would require everyone to tweak their webpack.config.js to transpile
node_modules stuff, or I transpile as much as possible. (Which is why the
Vue files have very little code in them)

Well, the strange thing is that the JS in the .Vue files still goes through
a transpiler (web browsers don't understand `export default`). This
transpiler comes from webpack. I mistakenly assumed that it was from Babel,
with the right settings, so I had included JavaScript arrow functions in
the code, which, surprise surprise wasn't transpiled into plain `function`.

Also, my testing pipeline currently only supports Chrome (headless). If you
know how to CI/CD with IE11, you're welcome to contribute.

**Comment by rokkie** [comment]
Just updated to v0.9.7. All seems to work fine!

**Comment by andrispraulitis** [comment]
BUT still does not work on IE11 importing modules from src

e.g import {GmapMarker} from 'vue2-google-maps/src/components/marker'

**Comment by rokkie** [comment]
@andrispraulitis try `import {GmapMarker} from 'vue2-google-maps/dist/components/marker'`.

**Comment by andrispraulitis** [comment]
Thats what I did but IE11 complained about arrow functions so something missing from your babel setup.

**Comment by crismith** [comment]
Hello community were able to fix this bugs of IE 11

**Comment by andrispraulitis** [comment]
The best fix would be to remove IE from planet earth :)
