### ISSUE TITLE
custom text field via scoped slot of Autocomplete does not working

### ISSUE THREAD

**Issue by ttlg** [xkjyeah/vue-google-maps#718]
I tried to use custom text field by exactly same way as it is mentioned at README like below. 
But it does not change at all.  Also it output no errors. 
Does anyone know the reason?
Or do you success to change text field via scoped slot?
```
          <gmap-autocomplete class="introInput" >
                    <template v-slot:input="slotProps">
                        <v-text-field outlined
                                      prepend-inner-icon="place"
                                      placeholder="Location Of Event"
                                      ref="input"
                                      v-on:listeners="slotProps.listeners"
                                      v-on:attrs="slotProps.attrs">
                        </v-text-field>
                    </template>
        </gmap-autocomplete>
```
The versions:
- "vue2-google-maps": "^0.10.7",
- "nuxt": "^2.12.2",
-  "@nuxtjs/vuetify": "^1.11.0",

**Comment by davydnorris** [comment]
The current npm package still doesn't include the additional code to enable scoped slots. Hopefully some time soon @xkjyeah will push an update

**Comment by josegus** [comment]
I'm more concerned by this deprecation notice
![image](https://user-images.githubusercontent.com/13947849/82521265-2a43b700-9af4-11ea-945e-a880c1fe89ce.png)

**Comment by davydnorris** [comment]
@diegoazh has very kindly forked this repo and has started to maintain this library, as well as releasing an updated npm package where this issue is now fixed, as well as flagging the deprecations above for work.

See [https://github.com/diegoazh/gmap-vue](https://github.com/diegoazh/gmap-vue)

**Comment by josegus** [comment]
> @diegoazh has very kindly forked this repo and has started to maintain this library, as well as releasing an updated npm package where this issue is now fixed, as well as flagging the deprecations above for work.
> 
> See https://github.com/diegoazh/gmap-vue

I've migrated to his repo a few minutes ago, but the deprecation notice still exists. Are you sure this is fixed?

**Comment by davydnorris** [comment]
If you have a look, there's an Issue logged just recently so it's in the pipeline to be fixed - it's a simple fix and the grace period is until November this year

**Comment by ttlg** [comment]
I confirmed I can use `v-slot:input` by using https://github.com/diegoazh/gmap-vue.
Thank you very much for your help.
